/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("jp.takuji31.kotlinfest2022.kotlin-application-conventions")
    id("com.google.devtools.ksp") version "1.7.21-1.0.8"
}

dependencies {
    implementation(projects.compiler)
    ksp(projects.compiler)
}

application {
    // Define the main class for the application.
    mainClass.set("jp.takuji31.kotlinfest2022.app.AppKt")
}

kotlin {
    sourceSets.main {
        kotlin.srcDir("build/generated/ksp/main/kotlin")
    }
    sourceSets.test {
        kotlin.srcDir("build/generated/ksp/test/kotlin")
    }
}
